---
title: "Venue"
sidebar: false
---

The venue for the workshop is [Curtin 139 St Georges Terrace](https://www.curtin.edu.au/about/campus-locations/st-georges-terrace/curtin-139-st-georges-terrace/) located at 139 St Georges Terrace, Perth, WA 6000.

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3385.242444947424!2d115.85464870000001!3d-31.9543188!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2a32bad5047e1871%3A0x934c4107a3eb1da8!2sCurtin%20139%20St%20Georges%20Terrace!5e0!3m2!1sen!2sau!4v1662001931905!5m2!1sen!2sau" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

## Public Transport

If you’re catching the train, disembark at the Elizabeth Quay station, head left after exiting the station, then up the escalator before crossing the pedestrian bridge on your right, and finally walking through Brookfield Place to the venue.

There are also numerous bus routes that service St Georges Terrace.

## Car Parks

There is no on-site parking, the closest public car parks are:

- Central Park, 152-158 St Georges Terrace, Perth.

- His Majesty’s, 377 Murray Street, Perth.

- Citipark (Wilson Parking), 427 Murray Street, Perth.

- Convention Centre, 21 Mounts Bay Rd and Mitchell Freeway, Perth.

## Catering

Morning tea and afternoon tea are included in the registration fee.

